-- ==========================================
-- 1. CREACIÓN DE TABLAS DE CATEGORÍAS Y UNIDADES
-- ==========================================

CREATE TABLE IF NOT EXISTS public.product_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.product_units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    abbreviation TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar RLS
ALTER TABLE public.product_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_units ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_full_access_product_categories" ON public.product_categories FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "authenticated_full_access_product_units" ON public.product_units FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- ==========================================
-- 2. MODIFICACIÓN DE LA TABLA PRODUCTS
-- ==========================================

ALTER TABLE public.products 
ADD COLUMN IF NOT EXISTS category_id BIGINT REFERENCES public.product_categories(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS unit_id BIGINT REFERENCES public.product_units(id) ON DELETE SET NULL;

-- Migración de datos existentes de "unit" (texto) a "product_units"
INSERT INTO public.product_units (name)
SELECT DISTINCT unit FROM public.products WHERE unit IS NOT NULL AND unit != ''
ON CONFLICT (name) DO NOTHING;

UPDATE public.products p
SET unit_id = pu.id
FROM public.product_units pu
WHERE p.unit = pu.name AND p.unit_id IS NULL;


-- ==========================================
-- 3. FUNCIONES RPC PARA REPORTES
-- ==========================================

-- REPORTE 1: Evolución de Ventas Mensuales
CREATE OR REPLACE FUNCTION rpc_get_sales_evolution(
    p_start_date DATE,
    p_end_date DATE
)
RETURNS TABLE (
    mes TEXT,
    unit_name TEXT,
    category_name TEXT,
    total_amount NUMERIC,
    total_quantity NUMERIC
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        TO_CHAR(s.date, 'YYYY-MM') AS mes,
        COALESCE(pu.name, 'Sin unidad') AS unit_name,
        COALESCE(pc.name, 'Sin categoría') AS category_name,
        SUM(si.total) AS total_amount,
        SUM(si.quantity) AS total_quantity
    FROM public.sales s
    JOIN public.sale_items si ON s.id = si.sale_id
    JOIN public.products p ON si.product_id = p.id
    LEFT JOIN public.product_units pu ON p.unit_id = pu.id
    LEFT JOIN public.product_categories pc ON p.category_id = pc.id
    WHERE s.date >= p_start_date AND s.date <= p_end_date
      AND s.status != 'cancelled'
    GROUP BY TO_CHAR(s.date, 'YYYY-MM'), pu.name, pc.name
    ORDER BY mes ASC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- REPORTE 2: Detalle de Ventas por Categoría
CREATE OR REPLACE FUNCTION rpc_get_sales_by_category(
    p_start_date DATE,
    p_end_date DATE,
    p_category_id BIGINT DEFAULT NULL
)
RETURNS TABLE (
    category_id BIGINT,
    category_name TEXT,
    unit_name TEXT,
    total_quantity NUMERIC,
    total_amount NUMERIC,
    avg_price NUMERIC
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        pc.id AS category_id,
        COALESCE(pc.name, 'Sin categoría') AS category_name,
        COALESCE(pu.name, 'Sin unidad') AS unit_name,
        SUM(si.quantity) AS total_quantity,
        SUM(si.total) AS total_amount,
        CASE WHEN SUM(si.quantity) > 0 THEN SUM(si.total) / SUM(si.quantity) ELSE 0 END AS avg_price
    FROM public.sales s
    JOIN public.sale_items si ON s.id = si.sale_id
    JOIN public.products p ON si.product_id = p.id
    LEFT JOIN public.product_units pu ON p.unit_id = pu.id
    LEFT JOIN public.product_categories pc ON p.category_id = pc.id
    WHERE s.date >= p_start_date AND s.date <= p_end_date
      AND s.status != 'cancelled'
      AND (p_category_id IS NULL OR p.category_id = p_category_id)
    GROUP BY pc.id, pc.name, pu.name
    ORDER BY total_amount DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- REPORTE 3: Clientes Activos e Inactivos
CREATE OR REPLACE FUNCTION rpc_get_clients_status(
    p_days INTEGER
)
RETURNS TABLE (
    client_id UUID,
    client_name TEXT,
    last_purchase_date DATE,
    days_inactive INTEGER,
    monthly_avg_purchase NUMERIC,
    is_active BOOLEAN
) AS $$
BEGIN
    RETURN QUERY
    WITH client_stats AS (
        SELECT 
            c.id,
            c.name,
            MAX(s.date) AS last_purchase_date,
            CURRENT_DATE - MAX(s.date) AS days_inactive,
            (SUM(s.total) / GREATEST(1, EXTRACT(MONTH FROM AGE(CURRENT_DATE, MIN(s.date))) + EXTRACT(YEAR FROM AGE(CURRENT_DATE, MIN(s.date))) * 12)) AS monthly_avg
        FROM public.clients c
        JOIN public.sales s ON c.id = s.client_id
        WHERE s.status != 'cancelled'
        GROUP BY c.id, c.name
    )
    SELECT 
        cs.id AS client_id,
        cs.name AS client_name,
        cs.last_purchase_date,
        cs.days_inactive,
        cs.monthly_avg AS monthly_avg_purchase,
        (cs.days_inactive <= p_days) AS is_active
    FROM client_stats cs;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- REPORTE 4: Retención y Nuevos Clientes
CREATE OR REPLACE FUNCTION rpc_get_clients_retention(
    p_start_date DATE,
    p_end_date DATE
)
RETURNS TABLE (
    mes TEXT,
    new_clients_count BIGINT,
    retained_clients_count BIGINT,
    total_active_clients BIGINT
) AS $$
BEGIN
    RETURN QUERY
    WITH monthly_sales AS (
        SELECT 
            TO_CHAR(s.date, 'YYYY-MM') AS month_str,
            s.client_id
        FROM public.sales s
        WHERE s.date >= (p_start_date - INTERVAL '1 month') AND s.date <= p_end_date
          AND s.status != 'cancelled'
        GROUP BY TO_CHAR(s.date, 'YYYY-MM'), s.client_id
    ),
    first_purchases AS (
        SELECT 
            client_id,
            TO_CHAR(MIN(date), 'YYYY-MM') AS first_month
        FROM public.sales
        WHERE status != 'cancelled'
        GROUP BY client_id
    )
    SELECT 
        m.month_str AS mes,
        COUNT(DISTINCT CASE WHEN fp.first_month = m.month_str THEN m.client_id END) AS new_clients_count,
        COUNT(DISTINCT CASE WHEN m_prev.client_id IS NOT NULL THEN m.client_id END) AS retained_clients_count,
        COUNT(DISTINCT m.client_id) AS total_active_clients
    FROM monthly_sales m
    LEFT JOIN first_purchases fp ON m.client_id = fp.client_id
    LEFT JOIN monthly_sales m_prev ON m.client_id = m_prev.client_id AND TO_DATE(m.month_str || '-01', 'YYYY-MM-DD') = (TO_DATE(m_prev.month_str || '-01', 'YYYY-MM-DD') + INTERVAL '1 month')
    WHERE TO_DATE(m.month_str || '-01', 'YYYY-MM-DD') >= p_start_date 
      AND TO_DATE(m.month_str || '-01', 'YYYY-MM-DD') <= p_end_date
    GROUP BY m.month_str
    ORDER BY m.month_str;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
