-- ==============================================================================
-- IMPORTANTE: Este archivo es una plantilla generada a partir del código.
-- Para tener la estructura EXACTA y completa de tu base de datos actual, 
-- el dueño original del proyecto debe exportarla desde Supabase así:
-- 
-- 1. Ir a Supabase Dashboard -> Project Settings -> Database
-- 2. Copiar el "Connection string" (URI)
-- 3. En la terminal local, ejecutar:
--    pg_dump -h db.[PROJECT-REF].supabase.co -U postgres -d postgres --schema-only > schema.sql
-- 
-- Alternativamente, si tienes el CLI de Supabase inicializado:
--    supabase db dump -f schema.sql
-- ==============================================================================

-- A continuación, se provee un esquema básico reconstruido según el código de la app:

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Tabla Profiles (Extendiendo auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    full_name TEXT,
    email TEXT UNIQUE NOT NULL,
    role TEXT DEFAULT 'usuario',
    permission TEXT DEFAULT 'limitado',
    status TEXT DEFAULT 'activo',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla de Usuarios (Backup/Legacy)
CREATE TABLE IF NOT EXISTS public.usuarios (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    usuario TEXT NOT NULL UNIQUE,
    contrasena TEXT NOT NULL,
    rol TEXT NOT NULL,
    estado TEXT NOT NULL
);

-- Zonas
CREATE TABLE IF NOT EXISTS public.zones (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL
);

-- Clientes
CREATE TABLE IF NOT EXISTS public.clients (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    address TEXT,
    zone_id UUID REFERENCES zones(id) ON DELETE SET NULL,
    balance NUMERIC(10, 2) DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Productos
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    description TEXT NOT NULL,
    unit TEXT,
    cost NUMERIC(10, 2) DEFAULT 0,
    base_price NUMERIC(10, 2) DEFAULT 0,
    current_stock NUMERIC(10, 2) DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Ventas
CREATE TABLE IF NOT EXISTS public.sales (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    client_id UUID REFERENCES clients(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    sale_type TEXT NOT NULL,
    status TEXT DEFAULT 'completed',
    total NUMERIC(10, 2) NOT NULL,
    is_delivered BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Ítems de Ventas
CREATE TABLE IF NOT EXISTS public.sale_items (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    sale_id UUID REFERENCES sales(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id),
    quantity NUMERIC(10, 2) NOT NULL,
    unit_price NUMERIC(10, 2) NOT NULL,
    total NUMERIC(10, 2) NOT NULL
);

-- Cobranzas
CREATE TABLE IF NOT EXISTS public.collections (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    client_id UUID REFERENCES clients(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    amount NUMERIC(10, 2) NOT NULL,
    payment_method TEXT,
    collector_id UUID REFERENCES auth.users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Cambios de Precios Programados
CREATE TABLE IF NOT EXISTS public.scheduled_price_changes (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    new_cost NUMERIC(10, 2) NOT NULL,
    new_base_price NUMERIC(10, 2) NOT NULL,
    effective_date TIMESTAMP WITH TIME ZONE NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending', 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Función para aplicar precios programados
CREATE OR REPLACE FUNCTION apply_scheduled_prices()
RETURNS void AS $$
BEGIN
    UPDATE products p
    SET cost = spc.new_cost, base_price = spc.new_base_price
    FROM scheduled_price_changes spc
    WHERE p.id = spc.product_id AND spc.status = 'pending' AND spc.effective_date <= NOW();

    UPDATE scheduled_price_changes
    SET status = 'applied'
    WHERE status = 'pending' AND effective_date <= NOW();
END;
$$ LANGUAGE plpgsql;

-- Reglas RLS Básicas (Descomentar para habilitar si es necesario)
-- ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;
