-- =============================================================================
-- APP HUEVOS — SCHEMA COMPLETO DE BASE DE DATOS
-- Generado desde análisis de api.js, schema.sql y db_updates.sql
-- Ejecutar en: Supabase Dashboard → SQL Editor
-- Orden de ejecución: de arriba hacia abajo (respeta FK dependencies)
-- =============================================================================

-- ---------------------------------------------------------------------------
-- EXTENSIONES
-- ---------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
-- pg_cron solo disponible en Supabase Pro/Team:
-- CREATE EXTENSION IF NOT EXISTS pg_cron;


-- =============================================================================
-- BLOQUE 1: TABLAS MAESTRAS (sin dependencias externas)
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.profiles (
    id              UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    full_name       TEXT,
    email           TEXT UNIQUE NOT NULL,
    role            TEXT        DEFAULT 'admin',
    permission      TEXT        DEFAULT 'total',
    status          TEXT        DEFAULT 'activo',
    is_approved     BOOLEAN     DEFAULT true,
    is_disabled     BOOLEAN     DEFAULT false,
    organization_id TEXT        DEFAULT 'empresa_principal',
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.usuarios (
    id         UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    usuario    TEXT NOT NULL UNIQUE,
    contrasena TEXT NOT NULL,
    rol        TEXT NOT NULL,
    estado     TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.zones (
    id            UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name          TEXT NOT NULL,
    delivery_days TEXT[]
);

CREATE TABLE IF NOT EXISTS public.products (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          TEXT UNIQUE NOT NULL,
    description   TEXT NOT NULL,
    unit          TEXT,
    cost          NUMERIC(12,2) DEFAULT 0,
    base_price    NUMERIC(12,2) DEFAULT 0,
    current_stock NUMERIC(12,2) DEFAULT 0,
    image_url     TEXT,
    created_at    TIMESTAMPTZ   DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.providers (
    id           UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name         TEXT NOT NULL,
    cuit         TEXT,
    cuit_fiscal  TEXT,
    address      TEXT,
    phone        TEXT,
    email        TEXT,
    balance      NUMERIC(12,2) DEFAULT 0,
    created_at   TIMESTAMPTZ   DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.price_lists (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.price_list_items (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    price_list_id BIGINT REFERENCES public.price_lists(id) ON DELETE CASCADE,
    product_id    BIGINT REFERENCES public.products(id)    ON DELETE CASCADE,
    price         NUMERIC(12,2) DEFAULT 0,
    discounts     JSONB,
    UNIQUE (price_list_id, product_id)
);

CREATE TABLE IF NOT EXISTS public.arqueo_categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE,
    description TEXT,
    is_default  BOOLEAN DEFAULT false,
    sort_order  INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.condicion_fiscal (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo      TEXT NOT NULL UNIQUE,
    descripcion TEXT NOT NULL,
    activo      BOOLEAN DEFAULT true
);

CREATE TABLE IF NOT EXISTS public.alicuotas_iva (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    porcentaje  NUMERIC(5,2) NOT NULL,
    descripcion TEXT         NOT NULL,
    codigo_afip INTEGER,
    activo      BOOLEAN DEFAULT true
);

CREATE TABLE IF NOT EXISTS public.tipo_comprobante (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo         TEXT NOT NULL UNIQUE,
    descripcion    TEXT NOT NULL,
    discrimina_iva BOOLEAN DEFAULT false,
    codigo_afip    INTEGER,
    activo         BOOLEAN DEFAULT true
);

CREATE TABLE IF NOT EXISTS public.regimenes_retencion (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      TEXT NOT NULL,
    impuesto    TEXT,
    organismo   TEXT,
    tipo        TEXT,
    alicuota    NUMERIC(6,4) DEFAULT 0,
    activo      BOOLEAN DEFAULT true
);

CREATE TABLE IF NOT EXISTS public.iibb_jurisdicciones (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      TEXT NOT NULL,
    codigo      TEXT,
    alicuota    NUMERIC(6,4) DEFAULT 0,
    activo      BOOLEAN DEFAULT true
);

CREATE TABLE IF NOT EXISTS public.empresa_config (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    razon_social        TEXT,
    nombre_fantasia     TEXT,
    cuit                TEXT,
    domicilio_fiscal    TEXT,
    localidad           TEXT,
    provincia           TEXT,
    cp                  TEXT,
    condicion_fiscal_id BIGINT REFERENCES public.condicion_fiscal(id),
    punto_venta_default INTEGER DEFAULT 1,
    logo_url            TEXT,
    activo              BOOLEAN DEFAULT true,
    created_at          TIMESTAMPTZ DEFAULT NOW(),
    updated_at          TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.arca_configuracion (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuit_emisor            TEXT,
    razon_social           TEXT,
    ambiente               TEXT DEFAULT 'homologacion',
    condicion_iva_emisor   TEXT,
    domicilio_fiscal       TEXT,
    localidad              TEXT,
    provincia              TEXT,
    cp                     TEXT,
    logo_url               TEXT,
    pie_factura            TEXT,
    email_envio_facturas   TEXT,
    email_proveedor        TEXT,
    activo                 BOOLEAN DEFAULT true,
    configuracion_completa BOOLEAN DEFAULT false,
    ws_token_expira        TIMESTAMPTZ,
    created_at             TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.arca_puntos_venta (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero      INTEGER NOT NULL UNIQUE,
    descripcion TEXT,
    tipo        TEXT DEFAULT 'web_services',
    activo      BOOLEAN DEFAULT true
);

CREATE TABLE IF NOT EXISTS public.arca_ws_log (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha     TIMESTAMPTZ DEFAULT NOW(),
    metodo    TEXT,
    request   JSONB,
    response  JSONB,
    exitoso   BOOLEAN,
    error_msg TEXT
);


-- =============================================================================
-- BLOQUE 2: TABLAS CON DEPENDENCIAS
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.clients (
    id            UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name          TEXT NOT NULL,
    address       TEXT,
    phone         TEXT,
    email         TEXT,
    cuit          TEXT,
    cuit_fiscal   TEXT,
    zone_id       UUID   REFERENCES public.zones(id)         ON DELETE SET NULL,
    price_list_id BIGINT REFERENCES public.price_lists(id)   ON DELETE SET NULL,
    parent_id     UUID   REFERENCES public.clients(id)       ON DELETE SET NULL,
    balance       NUMERIC(12,2) DEFAULT 0,
    created_at    TIMESTAMPTZ   DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.sales (
    id           UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    client_id    UUID REFERENCES public.clients(id) ON DELETE CASCADE,
    date         DATE          NOT NULL,
    sale_type    TEXT          NOT NULL,
    status       TEXT          DEFAULT 'pending',
    total        NUMERIC(12,2) NOT NULL,
    is_delivered BOOLEAN       DEFAULT false,
    currency     TEXT          DEFAULT 'ARS',
    user_id      UUID REFERENCES auth.users(id),
    created_by   UUID REFERENCES auth.users(id),
    created_at   TIMESTAMPTZ   DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.sale_items (
    id               UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    sale_id          UUID   REFERENCES public.sales(id)    ON DELETE CASCADE,
    product_id       BIGINT REFERENCES public.products(id),
    quantity         NUMERIC(12,2) NOT NULL,
    unit_price       NUMERIC(12,2) NOT NULL,
    unit_cost        NUMERIC(12,2) DEFAULT 0,
    total            NUMERIC(12,2) NOT NULL,
    discount_applied JSONB
);

CREATE TABLE IF NOT EXISTS public.collections (
    id                 UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    client_id          UUID   REFERENCES public.clients(id) ON DELETE CASCADE,
    date               DATE          NOT NULL,
    amount             NUMERIC(12,2) NOT NULL,
    payment_method     TEXT,
    observations       TEXT,
    collector_id       UUID   REFERENCES auth.users(id),
    currency           TEXT          DEFAULT 'ARS',
    arqueo_category_id BIGINT REFERENCES public.arqueo_categories(id) ON DELETE SET NULL,
    created_by         UUID   REFERENCES auth.users(id),
    created_at         TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.client_adjustments (
    id          UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    client_id   UUID REFERENCES public.clients(id) ON DELETE CASCADE,
    amount      NUMERIC(12,2) NOT NULL,
    type        TEXT,
    description TEXT,
    date        DATE,
    created_by  UUID REFERENCES auth.users(id),
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.expenses (
    id                 UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    description        TEXT,
    amount             NUMERIC(12,2) NOT NULL,
    date               DATE          NOT NULL,
    category           TEXT,
    user_id            UUID   REFERENCES auth.users(id),
    currency           TEXT          DEFAULT 'ARS',
    arqueo_category_id BIGINT REFERENCES public.arqueo_categories(id) ON DELETE SET NULL,
    provider_id        UUID   REFERENCES public.providers(id) ON DELETE SET NULL,
    created_by         UUID   REFERENCES auth.users(id),
    created_at         TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.purchases (
    id          UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    provider_id UUID   REFERENCES public.providers(id) ON DELETE SET NULL,
    date        DATE          NOT NULL,
    status      TEXT          DEFAULT 'completed',
    total       NUMERIC(12,2) NOT NULL,
    user_id     UUID   REFERENCES auth.users(id),
    created_by  UUID   REFERENCES auth.users(id),
    created_at  TIMESTAMPTZ   DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.purchase_items (
    id          UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    purchase_id UUID   REFERENCES public.purchases(id)  ON DELETE CASCADE,
    product_id  BIGINT REFERENCES public.products(id),
    quantity    NUMERIC(12,2) NOT NULL,
    unit_price  NUMERIC(12,2) NOT NULL,
    total       NUMERIC(12,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.provider_adjustments (
    id          UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    provider_id UUID REFERENCES public.providers(id) ON DELETE CASCADE,
    amount      NUMERIC(12,2) NOT NULL,
    type        TEXT,
    description TEXT,
    date        DATE,
    created_by  UUID REFERENCES auth.users(id),
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.transfers (
    id               UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    from_user_id     UUID   REFERENCES auth.users(id),
    to_user_id       UUID   REFERENCES auth.users(id),
    amount           NUMERIC(12,2) NOT NULL,
    currency         TEXT          DEFAULT 'ARS',
    date             DATE          NOT NULL,
    description      TEXT,
    from_category_id BIGINT REFERENCES public.arqueo_categories(id) ON DELETE SET NULL,
    to_category_id   BIGINT REFERENCES public.arqueo_categories(id) ON DELETE SET NULL,
    created_at       TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.scheduled_price_changes (
    id             UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    product_id     BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    new_cost       NUMERIC(12,2) NOT NULL,
    new_base_price NUMERIC(12,2) NOT NULL,
    effective_date TIMESTAMPTZ   NOT NULL,
    status         TEXT NOT NULL DEFAULT 'pending',
    created_at     TIMESTAMPTZ   DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.audit_logs (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name            TEXT,
    operation             TEXT,
    record_id             TEXT,
    responsible_full_name TEXT,
    responsible_email     TEXT,
    editor_full_name      TEXT,
    editor_email          TEXT,
    old_data              JSONB,
    new_data              JSONB,
    created_at            TIMESTAMPTZ DEFAULT NOW()
);


-- =============================================================================
-- BLOQUE 3: MODULO FISCAL
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.comprobantes (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flujo                   TEXT NOT NULL,
    tipo_comprobante_id     BIGINT REFERENCES public.tipo_comprobante(id),
    punto_venta             INTEGER DEFAULT 1,
    numero                  BIGINT,
    fecha_emision           DATE NOT NULL,
    fecha_vto_pago          DATE,
    cliente_id              UUID REFERENCES public.clients(id)   ON DELETE SET NULL,
    proveedor_id            UUID REFERENCES public.providers(id) ON DELETE SET NULL,
    condicion_iva_receptor  TEXT,
    cuit_receptor           TEXT,
    razon_social_receptor   TEXT,
    neto_gravado_27         NUMERIC(14,2) DEFAULT 0,
    neto_gravado_21         NUMERIC(14,2) DEFAULT 0,
    neto_gravado_105        NUMERIC(14,2) DEFAULT 0,
    neto_gravado_0          NUMERIC(14,2) DEFAULT 0,
    neto_no_gravado         NUMERIC(14,2) DEFAULT 0,
    neto_exento             NUMERIC(14,2) DEFAULT 0,
    iva_27                  NUMERIC(14,2) DEFAULT 0,
    iva_21                  NUMERIC(14,2) DEFAULT 0,
    iva_105                 NUMERIC(14,2) DEFAULT 0,
    total_otros_tributos    NUMERIC(14,2) DEFAULT 0,
    total_comprobante       NUMERIC(14,2) NOT NULL,
    estado                  TEXT DEFAULT 'emitido',
    anulado                 BOOLEAN DEFAULT false,
    periodo_fiscal          TEXT,
    comprobante_original_id BIGINT REFERENCES public.comprobantes(id) ON DELETE SET NULL,
    cae                     TEXT,
    cae_vto                 DATE,
    created_by              UUID REFERENCES auth.users(id),
    created_at              TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.comprobante_items (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comprobante_id       BIGINT REFERENCES public.comprobantes(id) ON DELETE CASCADE,
    producto_id          BIGINT REFERENCES public.products(id)     ON DELETE SET NULL,
    descripcion          TEXT,
    cantidad             NUMERIC(12,4) DEFAULT 1,
    precio_unitario_neto NUMERIC(14,4) NOT NULL,
    alicuota_iva_id      BIGINT REFERENCES public.alicuotas_iva(id) ON DELETE SET NULL,
    iva_importe          NUMERIC(14,2) DEFAULT 0,
    tipo_gravamen        TEXT DEFAULT 'gravado',
    total_item           NUMERIC(14,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.retenciones_percepciones (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comprobante_id   BIGINT REFERENCES public.comprobantes(id) ON DELETE CASCADE,
    regimen_id       BIGINT REFERENCES public.regimenes_retencion(id) ON DELETE SET NULL,
    tipo             TEXT NOT NULL,
    base_imponible   NUMERIC(14,2) DEFAULT 0,
    alicuota         NUMERIC(6,4)  DEFAULT 0,
    importe          NUMERIC(14,2) NOT NULL,
    nro_certificado  TEXT,
    fecha            DATE,
    cuit_agente      TEXT,
    periodo_fiscal   TEXT,
    ingresado_manual BOOLEAN DEFAULT false
);

CREATE TABLE IF NOT EXISTS public.periodos_fiscales (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anio                  INTEGER NOT NULL,
    mes                   INTEGER NOT NULL,
    debito_fiscal         NUMERIC(14,2) DEFAULT 0,
    credito_fiscal        NUMERIC(14,2) DEFAULT 0,
    retenciones_sufridas  NUMERIC(14,2) DEFAULT 0,
    percepciones_sufridas NUMERIC(14,2) DEFAULT 0,
    saldo_tecnico         NUMERIC(14,2) DEFAULT 0,
    iva_a_pagar           NUMERIC(14,2) DEFAULT 0,
    cerrado               BOOLEAN DEFAULT false,
    fecha_cierre          TIMESTAMPTZ,
    cerrado_por           UUID REFERENCES auth.users(id),
    UNIQUE(anio, mes)
);

CREATE TABLE IF NOT EXISTS public.auditoria_comprobantes (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comprobante_id BIGINT REFERENCES public.comprobantes(id) ON DELETE CASCADE,
    usuario_id     UUID REFERENCES auth.users(id),
    accion         TEXT,
    detalle        TEXT,
    created_at     TIMESTAMPTZ DEFAULT NOW()
);


-- =============================================================================
-- BLOQUE 4: FUNCIONES DE BASE DE DATOS
-- =============================================================================

CREATE OR REPLACE FUNCTION public.apply_scheduled_prices()
RETURNS void AS $$
BEGIN
    UPDATE public.products p
    SET cost = spc.new_cost, base_price = spc.new_base_price
    FROM public.scheduled_price_changes spc
    WHERE p.id = spc.product_id
      AND spc.status = 'pending'
      AND spc.effective_date <= NOW();

    UPDATE public.scheduled_price_changes
    SET status = 'applied'
    WHERE status = 'pending' AND effective_date <= NOW();
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.calcular_liquidacion_iva(p_anio INTEGER, p_mes INTEGER)
RETURNS TABLE (
    debito_fiscal         NUMERIC,
    credito_fiscal        NUMERIC,
    retenciones_sufridas  NUMERIC,
    percepciones_sufridas NUMERIC,
    saldo_tecnico         NUMERIC,
    iva_a_pagar           NUMERIC
) AS $$
DECLARE
    v_periodo TEXT := LPAD(p_anio::TEXT, 4, '0') || LPAD(p_mes::TEXT, 2, '0');
BEGIN
    RETURN QUERY
    SELECT
        COALESCE(SUM(CASE WHEN c.flujo = 'ventas'  AND NOT c.anulado THEN c.iva_21 + c.iva_105 + c.iva_27 ELSE 0 END), 0),
        COALESCE(SUM(CASE WHEN c.flujo = 'compras' AND NOT c.anulado THEN c.iva_21 + c.iva_105 + c.iva_27 ELSE 0 END), 0),
        COALESCE((SELECT SUM(rp.importe) FROM public.retenciones_percepciones rp WHERE rp.periodo_fiscal = v_periodo AND rp.tipo = 'retencion'), 0),
        COALESCE((SELECT SUM(rp.importe) FROM public.retenciones_percepciones rp WHERE rp.periodo_fiscal = v_periodo AND rp.tipo = 'percepcion'), 0),
        COALESCE(SUM(CASE WHEN c.flujo = 'ventas'  AND NOT c.anulado THEN c.iva_21 + c.iva_105 + c.iva_27 ELSE 0 END), 0)
        - COALESCE(SUM(CASE WHEN c.flujo = 'compras' AND NOT c.anulado THEN c.iva_21 + c.iva_105 + c.iva_27 ELSE 0 END), 0),
        GREATEST(0,
            COALESCE(SUM(CASE WHEN c.flujo = 'ventas'  AND NOT c.anulado THEN c.iva_21 + c.iva_105 + c.iva_27 ELSE 0 END), 0)
            - COALESCE(SUM(CASE WHEN c.flujo = 'compras' AND NOT c.anulado THEN c.iva_21 + c.iva_105 + c.iva_27 ELSE 0 END), 0)
            - COALESCE((SELECT SUM(rp.importe) FROM public.retenciones_percepciones rp WHERE rp.periodo_fiscal = v_periodo AND rp.tipo IN ('retencion','percepcion')), 0)
        )
    FROM public.comprobantes c
    WHERE c.periodo_fiscal = v_periodo;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
    user_count INTEGER;
BEGIN
    SELECT count(*) INTO user_count FROM public.profiles;
    
    INSERT INTO public.profiles (id, email, full_name, role, permission, status, is_approved, is_disabled)
    VALUES (
        NEW.id,
        NEW.email,
        COALESCE(NEW.raw_user_meta_data->>'full_name', split_part(NEW.email, '@', 1)),
        CASE WHEN user_count = 0 THEN 'admin' ELSE 'usuario' END,
        CASE WHEN user_count = 0 THEN 'total' ELSE 'limitado' END,
        'activo',
        true,
        false
    )
    ON CONFLICT (id) DO UPDATE SET
        role = EXCLUDED.role,
        is_approved = true;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- =============================================================================
-- BLOQUE 5: TRIGGERS
-- =============================================================================

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- =============================================================================
-- BLOQUE 6: ROW LEVEL SECURITY (RLS)
-- =============================================================================

ALTER TABLE public.profiles               ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zones                  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products               ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.price_lists            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.price_list_items       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients                ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales                  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sale_items             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.collections            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.client_adjustments     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.providers              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses               ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchases              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_items         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.provider_adjustments   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transfers              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.arqueo_categories      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scheduled_price_changes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.condicion_fiscal       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alicuotas_iva          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tipo_comprobante       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.regimenes_retencion    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.iibb_jurisdicciones    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.empresa_config         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comprobantes           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comprobante_items      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.retenciones_percepciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.periodos_fiscales      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.auditoria_comprobantes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.arca_configuracion     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.arca_puntos_venta      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.arca_ws_log            ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE
    tbl TEXT;
    tbls TEXT[] := ARRAY[
        'profiles','usuarios','zones','products','price_lists','price_list_items',
        'clients','sales','sale_items','collections','client_adjustments',
        'providers','expenses','purchases','purchase_items','provider_adjustments',
        'transfers','arqueo_categories','scheduled_price_changes','audit_logs',
        'condicion_fiscal','alicuotas_iva','tipo_comprobante','regimenes_retencion',
        'iibb_jurisdicciones','empresa_config','comprobantes','comprobante_items',
        'retenciones_percepciones','periodos_fiscales','auditoria_comprobantes',
        'arca_configuracion','arca_puntos_venta','arca_ws_log'
    ];
BEGIN
    FOREACH tbl IN ARRAY tbls LOOP
        EXECUTE format(
            'CREATE POLICY "authenticated_full_access_%s" ON public.%I FOR ALL TO authenticated USING (true) WITH CHECK (true)',
            tbl, tbl
        );
    END LOOP;
END $$;


-- =============================================================================
-- BLOQUE 7: CRON JOB (requiere pg_cron en Supabase Pro)
-- =============================================================================
-- SELECT cron.schedule('apply-scheduled-prices', '* * * * *', 'SELECT public.apply_scheduled_prices()');


-- =============================================================================
-- BLOQUE 8: STORAGE BUCKET
-- =============================================================================
-- Crear en Supabase Dashboard -> Storage:
--   Nombre: products | Publico: true | MIME types: image/*
